task 1

diff --git a/basics_1/1-show_attached_IPs b/basics_1/1-show_attached_IPs
--- a/basics_1/1-show_attached_IPs
+++ b/basics_1/1-show_attached_IPs
@@ -1,4 +1,9 @@
 #!/usr/bin/env bash
 # Script that displays all active IPv4 IPs on the machine it’s executed on
 
-ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1
+if ifconfig &>/dev/null; then
+    ifconfig | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
+else
+    echo "ifconfig command not found"
+    exit 1
+fi
